#
# Copyright (c) 2024 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Disable the unsupported driver
CONFIG_NRFX_UARTE0=n
# SPI buffer size for large transfers (4KB)
CONFIG_SPI_NRFX_RAM_BUFFER_SIZE=4096